/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Store = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Price = IDL.Record({
  'itemId' : IDL.Text,
  'storeId' : IDL.Text,
  'price' : IDL.Float64,
});
export const Item = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });

export const idlService = IDL.Service({
  'getAllPrices' : IDL.Func(
      [],
      [
        IDL.Record({
          'stores' : IDL.Vec(Store),
          'prices' : IDL.Vec(Price),
          'items' : IDL.Vec(Item),
        }),
      ],
      ['query'],
    ),
  'getBasketSuggestion' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [
        IDL.Record({
          'bestTotal' : IDL.Float64,
          'totalPerStore' : IDL.Vec(IDL.Tuple(Store, IDL.Float64)),
          'bestStore' : Store,
        }),
      ],
      ['query'],
    ),
  'getBestDeals' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            Item,
            IDL.Record({ 'store' : Store, 'price' : IDL.Float64 }),
          )
        ),
      ],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Store = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Price = IDL.Record({
    'itemId' : IDL.Text,
    'storeId' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Item = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  
  return IDL.Service({
    'getAllPrices' : IDL.Func(
        [],
        [
          IDL.Record({
            'stores' : IDL.Vec(Store),
            'prices' : IDL.Vec(Price),
            'items' : IDL.Vec(Item),
          }),
        ],
        ['query'],
      ),
    'getBasketSuggestion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [
          IDL.Record({
            'bestTotal' : IDL.Float64,
            'totalPerStore' : IDL.Vec(IDL.Tuple(Store, IDL.Float64)),
            'bestStore' : Store,
          }),
        ],
        ['query'],
      ),
    'getBestDeals' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              Item,
              IDL.Record({ 'store' : Store, 'price' : IDL.Float64 }),
            )
          ),
        ],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };